# 应用开关 true | false

# 是否能够在铁砧中使用
Anvil: true
# 是否在有战利品的箱子中出现
Chest: true
# 是否可以通过附魔台获得
EnchantTable: true
# 是否应用于自然生成的怪物身上
Mobs: true
# 是否应用于村民交易
Villager: true
# 是否应用于钓鱼获取
Fishing: true

#附魔:
# Enable:开/关
# DisplayName: 显示名称
# Chance :出现概率(0~1)
DE_PROTECTION:
  Enable: true
  DisplayName: "&7保护不能"
  Chance: 0.2
DE_FIRE_PROTECTION:
  Enable: true
  DisplayName: "&7火焰灼烧"
  Chance: 0.2
DE_FEATHER_FALLING:
  Enable: true
  DisplayName: "&7摔落骨折"
  Chance: 0.2
DE_BLAST_PROTECTION:
  Enable: true
  DisplayName: "&7瞬间爆炸"
  Chance: 0.2
DE_PROJECTILE_PROTECTION:
  Enable: true
  DisplayName: "&7弹射物吸引"
  Chance: 0.2
DE_RESPIRATION:
  Enable: true
  DisplayName: "&7水下窒息"
  Chance: 0.2
DE_AQUA_AFFINITY:
  Enable: true
  DisplayName: "&7水下慢掘"
  Chance: 0.2
DE_THORNS:
  Enable: true
  DisplayName: "&7负荆请罪"
  Chance: 0.2
DE_DEPTH_STRIDER:
  Enable: true
  DisplayName: "&7旱鸭子"
  Chance: 0.2
DE_FROST_WALKER:
  Enable: true
  DisplayName: "&7熔岩行者"
  Chance: 0.2
DE_BINDING_CURSE:
  Enable: true
  DisplayName: "&a灵魂绑定"
  Chance: 0.2
DE_SHARPNESS:
  Enable: true
  DisplayName: "&7磨钝"
  Chance: 0.2
DE_SMITE:
  Enable: true
  DisplayName: "&7亡灵救赎"
  Chance: 0.2
DE_BANE_OF_ARTHROPODS:
  Enable: true
  DisplayName: "&7节肢救星"
  Chance: 0.2
DE_KNOCKBACK:
  Enable: true
  DisplayName: "&7退击"
  Chance: 0.2
DE_FIRE_ASPECT:
  Enable: true
  DisplayName: "&7引火烧身"
  Chance: 0.2
DE_LOOTING:
  Enable: true
  DisplayName: "&7知足"
  Chance: 0.2
DE_SWEEPING:
  Enable: true
  DisplayName: "&7横扫失败"
  Chance: 0.2
DE_EFFICIENCY:
  Enable: true
  DisplayName: "&7低效"
  Chance: 0.2
DE_SILK_TOUCH:
  Enable: true
  DisplayName: "&7彻底粉碎"
  Chance: 0.2
DE_UNBREAKING:
  Enable: true
  DisplayName: "&7易损"
  Chance: 0.2
DE_FORTUNE:
  Enable: true
  DisplayName: "&7时运不济"
  Chance: 0.2
DE_POWER:
  Enable: true
  DisplayName: "&7虚弱"
  Chance: 0.2
DE_PUNCH:
  Enable: true
  DisplayName: "&7吸引"
  Chance: 0.2
DE_FLAME:
  Enable: true
  DisplayName: "&7神速"
  Chance: 0.2
DE_INFINITY:
  Enable: true
  DisplayName: "&7多重"
  Chance: 0.2
DE_LUCK_OF_THE_SEA:
  Enable: true
  DisplayName: "&7海之嫌弃"
  Chance: 0.2
DE_LURE:
  Enable: true
  DisplayName: "&7过期钓饵"
  Chance: 0.2
DE_LOYALTY:
  Enable: true
  DisplayName: "&7背叛"
  Chance: 0.2
DE_IMPALING:
  Enable: true
  DisplayName: "&7刺穿"
  Chance: 0.2
DE_RIPTIDE:
  Enable: true
  DisplayName: "&7逆流"
  Chance: 0.2
DE_CHANNELING:
  Enable: true
  DisplayName: "&7避雷针"
  Chance: 0.2
DE_MULTISHOT:
  Enable: true
  DisplayName: "&7连珠"
  Chance: 0.2
DE_QUICK_CHARGE:
  Enable: true
  DisplayName: "&7慢速填充"
  Chance: 0.2
DE_PIERCING:
  Enable: true
  DisplayName: "&7反弹"
  Chance: 0.2
DE_MENDING:
  Enable: true
  DisplayName: "&7经验反哺"
  Chance: 0.2
DE_VANISHING_CURSE:
  Enable: true
  DisplayName: "&7永存祝福"
  Chance: 0.2
DE_SOUL_SPEED:
  Enable: true
  DisplayName: "&7灵魂爬行"
  Chance: 0.2